# Generated by Django 2.1.10 on 2020-04-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20200416_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
