# Generated by Django 3.0.5 on 2020-04-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20200405_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nic',
            old_name='ipaddrs',
            new_name='address',
        ),
    ]
