# Generated by Django 2.1.10 on 2020-04-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20200416_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='abbreviation_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='缩写名'),
        ),
        migrations.AddField(
            model_name='env',
            name='abbreviation_name',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='缩写名'),
        ),
    ]
