# Generated by Django 3.0.5 on 2020-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20200405_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='device_status_id',
            field=models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1, null=True, verbose_name='服务器状态'),
        ),
        migrations.AlterField(
            model_name='server',
            name='device_type_id',
            field=models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1, null=True, verbose_name='服务器类型'),
        ),
    ]
