# Generated by Django 2.1.10 on 2020-04-16 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20200416_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='business_unit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.BusinessUnit', verbose_name='属于的业务线'),
        ),
        migrations.AlterField(
            model_name='server',
            name='env',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Env', verbose_name='所属环境'),
        ),
    ]
