# Generated by Django 3.0.5 on 2020-04-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20200405_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='系统版本'),
        ),
    ]
