# Generated by Django 3.0.5 on 2020-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20200405_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='tag',
            field=models.ManyToManyField(default='linux', to='cmdb.Tag'),
        ),
    ]
