# Generated by Django 3.0.5 on 2020-04-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20200405_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
