# Generated by Django 3.0.5 on 2020-04-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20200405_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cabinet_num',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cabinet_order',
        ),
        migrations.RemoveField(
            model_name='server',
            name='device_status_id',
        ),
        migrations.RemoveField(
            model_name='server',
            name='device_type_id',
        ),
        migrations.RemoveField(
            model_name='server',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='server',
            name='tag',
        ),
    ]
