# Generated by Django 2.1.10 on 2020-04-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_auto_20200416_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='tag',
            field=models.ManyToManyField(default=1, to='cmdb.Tag'),
        ),
    ]
