# Generated by Django 2.1.10 on 2020-04-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_auto_20200416_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='abbreviation_name',
            field=models.CharField(max_length=32, null=True, verbose_name='缩写名'),
        ),
    ]
