# Generated by Django 2.1.10 on 2020-04-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_businessunit_abbreviation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='ssh_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='ssh端口号'),
        ),
    ]
